default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: roshambo

development:
  <<: *default

test:
  <<: *default
  database: roshambo_test

postgresql:
  adapter: postgresql
  database: roshambo
  timeout: 5000
  pool: 5
